trigger:
- master   # runs when code is pushed to main branch

pool:
 vmImage: 'ubuntu-latest'
steps:
- script: maven validate
  displayName: 'Maven Validate'

- script: maven compile
  displayName: 'Maven Compile'